language: node_js

install:
  - npm install

script:
  - npm -v
  - node -v

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      branch: beta

notifications:
  email:
    on_success: never
